### ISSUE TITLE
Ukrainian localisation

### ISSUE THREAD

**Issue by ghaiklor** [ghaiklor/type-challenges-solutions#11]

**Comment by bdvorianov** [comment]
Me and @rosyurch will prepare localisation for existing solutions in [this fork](https://github.com/bdvorianov/type-challenges-solutions).

@rosyurch is working on:
+ index.md
+ easy-if
+ easy-includes
+ easy-pick

My files in progress now are:
+ easy-awaited
+ easy-concat
+ easy-exclude
+ easy-first

New updates will appear here as well.

**Comment by bdvorianov** [comment]
First chunk is reviewed and merged into my fork, next step we will migrate to this repo and take these files:

Me:
+ easy-readonly.md
+ easy-tuple-length.md
+ easy-tuple-to-object.md

@rosyurch:
medium-append-argument.md
medium-append-to-object.md
medium-camelcase.md

**Comment by bdvorianov** [comment]
Done:

+ easy-readonly.md
+ easy-tuple-length.md
+ easy-tuple-to-object.md
+ medium-capitalize.md

Next I will take:

+ medium-chainable-options.md
+ medium-deep-readonly.md
+ medium-diff.md
+ medium-flatten.md

**Comment by rosyurch** [comment]
Done: 

- medium-append-argument.md
- medium-append-to-object.md
- medium-camelcase.md

I'll take:

- medium-readonly-2.md
- medium-replace.md
- medium-replaceall.md

**Comment by ghaiklor** [comment]
Thanks to all of you! In the meantime, I gradually rollout translation to the website on the go. It would be great if you translate an `index.md` where the table with challenges is building (it is already on the website).

**Comment by rosyurch** [comment]
> 
> 
> Thanks to all of you! In the meantime, I gradually rollout translation to the website on the go. It would be great if you translate an `index.md` where the table with challenges is building (it is already on the website).

Pretty sure i did index.md in @bdvorianov 's fork

**Comment by ghaiklor** [comment]
I have updated the README, so it includes the contributors. Please, provide your e-mails, so I can sign commits with you as authors.

**Comment by ghaiklor** [comment]
Hey guys,

In case you are working with the translation, where can I grab them?

**Comment by A-Ostrovnyy** [comment]
Done:
* medium-omit.md
* medium-permutation.md
* medium-pop.md
* medium-promise-all.md

[All my translations](https://github.com/bdvorianov/type-challenges-solutions/pull/5)

**Comment by ghaiklor** [comment]
@A-Ostrovnyy moved:

- https://github.com/ghaiklor/type-challenges-solutions/commit/6675e122d81df1a3deb27e271035a5be2cb7463e
- https://github.com/ghaiklor/type-challenges-solutions/commit/f05d187036a376616009483975260d904563fdb8
- https://github.com/ghaiklor/type-challenges-solutions/commit/89f4fa0d11698236cadc0024c60b06d927342dbe
- https://github.com/ghaiklor/type-challenges-solutions/commit/de7fd6f6f4802204d80950341d4130f2f0f4753f
- https://github.com/ghaiklor/type-challenges-solutions/commit/ae400e77c728332bff248749315f1ebf7bae5644
- https://github.com/ghaiklor/type-challenges-solutions/commit/6a64cae5464d0bd55dbf0c56ff231549ce76ce6f
- https://github.com/ghaiklor/type-challenges-solutions/commit/401890a00c218cb5d0bdb6c1842c09ed6f15f01f
- https://github.com/ghaiklor/type-challenges-solutions/commit/7cec2ddc210a4827bb4afe4143a8daf6aeda9193

Worth mentioning that there were simple typos (a lot) that you could prevent by installing a spell checker for your IDE.

Also, I'm asking you not to translate from Russian to Ukrainian. The source language is English. I'm translating from English to Russian that you translate again to Ukrainian. It results in messy text with missed parts of sentences, and a lot of them just make little sense.

@bdvorianov @rosyurch please, can you proofread those commits and make tiny fixes (reminder, you can do it via GitHub UI).

Thanks everyone!

**Comment by ghaiklor** [comment]
I'm closing the issue and moving it to my to do list. Most work in this repository is done, including all the build processes and majority of content. There are left-overs that can be managed on the fly and have no specific deadlines. Will keep in touch with @bdvorianov and @shalamai in Telegram to sync the updates on the content. Thanks everyone!
