### ISSUE TITLE
Request helping on Chinese translation

### ISSUE THREAD

**Issue by charleserious** [ghaiklor/type-challenges-solutions#140]
Hello @likui628, 

I'm Chinese, and I saw you're contributing the Chinese translation, currently, I use TypeScript in my daily work.

If I may, I can help you with the Chinese translation.

Please let me offer my contribution, thx.

cc @ghaiklor

**Comment by ghaiklor** [comment]
@likui628 do you need any help? You could split the work and take different solutions for each of you. Anything that is still in progress can be checked by calling the sync command - `bundle exec ruby _scripts/sync-challenges.rb zh`

**Comment by charleserious** [comment]
@ghaiklor seems @likui628 not around

**Comment by likui628** [comment]
@charleserious 人多力量大，欢迎

@ghaiklor Yes, we can translate together and review each other's translation PR.

**Comment by ghaiklor** [comment]
So we can close this issue then. It's good you made a contact 👍🏻

**Comment by charleserious** [comment]
@ghaiklor so, please send me an invitation of the repo once you're free, so that I can tweak a little bit, thx though.

**Comment by ghaiklor** [comment]
@charleserious sure, I'll send an invite in a minute.
