### ISSUE TITLE
中文术语翻译

### ISSUE THREAD

**Issue by likui628** [ghaiklor/type-challenges-solutions#147]
这个 issue 帖用于讨论确定翻译用语。

|en|zh|
|---|---|
|Challenge|挑战|
|Solution|解答|
|References|参考|
|variadic tuple types|可变元组类型|
|type inference|类型推导|
|conditional types|条件类型|
|generic|泛型|
|flat type|普通类型|
|intersection types|交叉类型|

**Comment by likui628** [comment]
How about translating 'solution' to  '解答' ?

**Comment by chenxiaoyao6228** [comment]
> 

From my point of view, both '解法' and '解答' are OK, we can just use '解答'

**Comment by ghaiklor** [comment]
Can we close this one, did you have an agreement?

**Comment by charleserious** [comment]
I agree with "解答" too, kind more written terms.
And we already have a [PR](https://github.com/ghaiklor/type-challenges-solutions/pull/153) that follow this convention.

**Comment by likui628** [comment]
> 

close it later, we can discuss more.

**Comment by charleserious** [comment]
@likui628 @chenxiaoyao6228 we may need a way for collaborate with each other of our translations, letting others know the solutions you're working on.
I think the draft PR is a nice way for that, after we picked the solutions we directly push a draft PR, so that others could avoid  duplicate works.
BTW, I'm curious how may of us are work on the Chinese translation? 
cc @ghaiklor

**Comment by likui628** [comment]
@charleserious Absolutely.
we three guys are working on the translation.

**Comment by ghaiklor** [comment]
You can have a checklist of translations, where you tick anything that is in progress or done. I can create another issue where you can do it. Maybe this one can be closed then.

**Comment by ghaiklor** [comment]
Here is the issue - https://github.com/ghaiklor/type-challenges-solutions/issues/171. Can you check if you are able to tick the boxes in the list?

**Comment by ghaiklor** [comment]
@charleserious what about having a `GLOSSARY.md` file in the root with language categories. There you can define all the words. Maybe other languages will join as well, although, I'm not sure in it. It's not a huge project, so there is definitely should be a balance between maintaining the project and expected result.

**Comment by charleserious** [comment]
@ghaiklor I've push a [PR](https://github.com/ghaiklor/type-challenges-solutions/pull/145) fulfill what we discussed here, and named the file `README.md`.
And forgive my pool ruby practice.

**Comment by likui628** [comment]
I have no idea. 
I still think it would be more convenient to discuss it here.

**Comment by ghaiklor** [comment]
@likui628 whatever suits you. I have no objection to have the glossary in the root anyway. The only thing that I'm thinking is that this file will be used by you only, which makes me think it has no usefulness in there 🤔

**Comment by charleserious** [comment]
I think we need a formal place to arrange our thoughts and to put our conclusions so that we can have a convenient way to collaborate with each other with the minimum effort.
And don't worry that we will overturn periodic summaries from time to time, that's reasonable.
@ghaiklor @likui628

**Comment by ghaiklor** [comment]
@charleserious let's add the meaning of the terms in the PR #172 and I'll wait the vote of @likui628. Once we came to the consensus about the `GLOSSARY.md` as a file, I'll merge the PR.

**Comment by likui628** [comment]
I find two examples for us.
1. [vuejs-translations/docs-zh-cn](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)
2. [zh-hans.reactjs.org](https://github.com/reactjs/zh-hans.reactjs.org/issues/2)

By now, the glossary is still in process. so I suggest using the issue temporarily. 
@ghaiklor @charleserious

**Comment by ghaiklor** [comment]
Ok, so waiting the PR to be ready to merge, including:

- [ ] `GLOSSARY.md` in the root of the repo (we are not a huge organisation, why complicating things)
- [ ] Having English and Chinese terms mapped
- [ ] Having a meaning of each mapping

Does everyone agree?

**Comment by likui628** [comment]
agree
