### ISSUE TITLE
Chainable Options

### ISSUE THREAD

**Issue by SUtengda** [ghaiklor/type-challenges-solutions#213]
This project is aimed at helping you better understand how the type system works, writing your own utilities, or just having fun with the challenges.

https://ghaiklor.github.io/type-challenges-solutions/ru/medium-chainable-options.html

**Comment by SUtengda** [comment]
A question about `  option<K extends string, V>(key: K, value: V): Chainable<O & { [P in K]: V }>` pls,  
Is there a way to generate directly a type `{K: V}` ? as K is already a key ?

**Comment by ghaiklor** [comment]
Closing as a “noise” in comments system. BTW, I forgot to answer—AFAIK, no, you can't write `{ K: V }` in the type system here.
