### ISSUE TITLE
Update easy-includes.md solution

### ISSUE THREAD

**Issue by webpig** [ghaiklor/type-challenges-solutions#73]
**Describe the bug**
```js
type Includes<T extends unknown[], U> = U extends T[number] ? true : false;
```
This is not true: 
![image](https://user-images.githubusercontent.com/24989439/129127921-5f3697a4-c9a8-4ab9-ba51-fc0c0b19d837.png)

**Comment by ghaiklor** [comment]
@webpig thanks for the report, we already discussed it in the comments here https://ghaiklor.github.io/type-challenges-solutions/en/easy-includes.html

**Comment by webpig** [comment]
> @webpig thanks for the report, we already discussed it in the comments here https://ghaiklor.github.io/type-challenges-solutions/en/easy-includes.html
> 
> P.S. I have a task in my to do list to update the solution.

OK!
