### ISSUE TITLE
Can I start Korean Translation?

### ISSUE THREAD

**Issue by kyeongsoosoo** [ghaiklor/type-challenges-solutions#83]
Hi, Can I start Ko Translation? Solutions in this page helped me a lot. 
It would be great to have a Korean version.

**Comment by ghaiklor** [comment]
@kyeongsoosoo sure, you can start by creating a folder with a language code for Korean and start adding Markdown there with the translation. Make sure that the metadata is there and up to date. I can help you by setting up the skeleton for it and you will add more on the fly there.

- [ ] create a folder `ko` in the root
- [ ] the file structure mirrors the structure of other solutions, including filenames

As far as I remember, that is all you need to do for getting a Korean version. In case I forgot something, please ping me for any further questions and I'll help you set it up.

Thanks for your contribution!

**Comment by kyeongsoosoo** [comment]
Thanks for your guide.
Now, I'm looking for a co-worker who can help with reviews. 
Will begin working soon!

**Comment by ghaiklor** [comment]
I'm closing the issue as resolved. If you have any other questions, please open a new issue 🙇🏻
